kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
  # apiServerAddress: "0.0.0.0"
  # apiServerPort: 6443
  podSubnet: 10.114.0.0/24
  serviceSubnet: 10.114.1.0/24
# add to the apiServer certSANs the name of the docker (dind)
# service in order to be able to reach the cluster through it
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: docker
nodes:
- role: control-plane
  image: kindest/node:v1.14.10@sha256:ce4355398a704fca68006f8a29f37aafb49f8fc2f64ede3ccd0d9198da910146
