app:
  chartsDir: build/e2e/charts
  environmentsDir: build/e2e/clusters

repos:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

- name: arhat-dev
  url: https://helm-charts.arhat.dev/

charts:
# prometheus-operator chart using v1beta1 CRD
- name: bitnami/kube-prometheus@1.1.0
  namespaceInTemplate: true

# prometheus-operator using v1 CRD
- name: prometheus-community/kube-prometheus-stack@12.7.0
  namespaceInTemplate: true

- name: emqx@v4.2.3
  git:
    url: https://github.com/emqx/emqx-rel
    path: deploy/charts/emqx

- name: arhat-dev/calico@latest
- name: arhat-dev/calico-node@latest
- name: arhat-dev/arhat@latest
- name: aranya@master
  local: {}
  namespaceInTemplate: true
