// +build !ignore_autogenerated

/*
Copyright 2020 The arhat.dev Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AMQPSpec) DeepCopyInto(out *AMQPSpec) {
	*out = *in
	if in.UserPassRef != nil {
		in, out := &in.UserPassRef, &out.UserPassRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AMQPSpec.
func (in *AMQPSpec) DeepCopy() *AMQPSpec {
	if in == nil {
		return nil
	}
	out := new(AMQPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureEventHubConfig) DeepCopyInto(out *AzureEventHubConfig) {
	*out = *in
	out.ConnectionStringSecretKeyRef = in.ConnectionStringSecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureEventHubConfig.
func (in *AzureEventHubConfig) DeepCopy() *AzureEventHubConfig {
	if in == nil {
		return nil
	}
	out := new(AzureEventHubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureIoTHubConfig) DeepCopyInto(out *AzureIoTHubConfig) {
	*out = *in
	out.ConnectionStringSecretKeyRef = in.ConnectionStringSecretKeyRef
	out.DeviceStatusPollInterval = in.DeviceStatusPollInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureIoTHubConfig.
func (in *AzureIoTHubConfig) DeepCopy() *AzureIoTHubConfig {
	if in == nil {
		return nil
	}
	out := new(AzureIoTHubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureIoTHubSpec) DeepCopyInto(out *AzureIoTHubSpec) {
	*out = *in
	out.IoTHub = in.IoTHub
	out.EventHub = in.EventHub
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureIoTHubSpec.
func (in *AzureIoTHubSpec) DeepCopy() *AzureIoTHubSpec {
	if in == nil {
		return nil
	}
	out := new(AzureIoTHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityBackoff) DeepCopyInto(out *ConnectivityBackoff) {
	*out = *in
	if in.InitialDelay != nil {
		in, out := &in.InitialDelay, &out.InitialDelay
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxDelay != nil {
		in, out := &in.MaxDelay, &out.MaxDelay
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityBackoff.
func (in *ConnectivityBackoff) DeepCopy() *ConnectivityBackoff {
	if in == nil {
		return nil
	}
	out := new(ConnectivityBackoff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivitySpec) DeepCopyInto(out *ConnectivitySpec) {
	*out = *in
	in.Timers.DeepCopyInto(&out.Timers)
	in.Backoff.DeepCopyInto(&out.Backoff)
	in.MQTT.DeepCopyInto(&out.MQTT)
	in.GRPC.DeepCopyInto(&out.GRPC)
	in.AMQP.DeepCopyInto(&out.AMQP)
	out.AzureIoTHub = in.AzureIoTHub
	out.GCPIoTCore = in.GCPIoTCore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivitySpec.
func (in *ConnectivitySpec) DeepCopy() *ConnectivitySpec {
	if in == nil {
		return nil
	}
	out := new(ConnectivitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectivityTimers) DeepCopyInto(out *ConnectivityTimers) {
	*out = *in
	if in.UnarySessionTimeout != nil {
		in, out := &in.UnarySessionTimeout, &out.UnarySessionTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectivityTimers.
func (in *ConnectivityTimers) DeepCopy() *ConnectivityTimers {
	if in == nil {
		return nil
	}
	out := new(ConnectivityTimers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeDevice) DeepCopyInto(out *EdgeDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeDevice.
func (in *EdgeDevice) DeepCopy() *EdgeDevice {
	if in == nil {
		return nil
	}
	out := new(EdgeDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeDeviceList) DeepCopyInto(out *EdgeDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EdgeDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeDeviceList.
func (in *EdgeDeviceList) DeepCopy() *EdgeDeviceList {
	if in == nil {
		return nil
	}
	out := new(EdgeDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeDeviceSpec) DeepCopyInto(out *EdgeDeviceSpec) {
	*out = *in
	in.Connectivity.DeepCopyInto(&out.Connectivity)
	in.Node.DeepCopyInto(&out.Node)
	in.Pod.DeepCopyInto(&out.Pod)
	out.Storage = in.Storage
	in.Network.DeepCopyInto(&out.Network)
	if in.Peripherals != nil {
		in, out := &in.Peripherals, &out.Peripherals
		*out = make([]PeripheralSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricsReporters != nil {
		in, out := &in.MetricsReporters, &out.MetricsReporters
		*out = make([]PeripheralBaseSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeDeviceSpec.
func (in *EdgeDeviceSpec) DeepCopy() *EdgeDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(EdgeDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeDeviceStatus) DeepCopyInto(out *EdgeDeviceStatus) {
	*out = *in
	out.Network = in.Network
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeDeviceStatus.
func (in *EdgeDeviceStatus) DeepCopy() *EdgeDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(EdgeDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldHook) DeepCopyInto(out *FieldHook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldHook.
func (in *FieldHook) DeepCopy() *FieldHook {
	if in == nil {
		return nil
	}
	out := new(FieldHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPCloudIoTConfig) DeepCopyInto(out *GCPCloudIoTConfig) {
	*out = *in
	out.CredentialsSecretKeyRef = in.CredentialsSecretKeyRef
	out.DeviceStatusPollInterval = in.DeviceStatusPollInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPCloudIoTConfig.
func (in *GCPCloudIoTConfig) DeepCopy() *GCPCloudIoTConfig {
	if in == nil {
		return nil
	}
	out := new(GCPCloudIoTConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPIoTCoreSpec) DeepCopyInto(out *GCPIoTCoreSpec) {
	*out = *in
	out.PubSub = in.PubSub
	out.CloudIoT = in.CloudIoT
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPIoTCoreSpec.
func (in *GCPIoTCoreSpec) DeepCopy() *GCPIoTCoreSpec {
	if in == nil {
		return nil
	}
	out := new(GCPIoTCoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPPubSubConfig) DeepCopyInto(out *GCPPubSubConfig) {
	*out = *in
	out.CredentialsSecretKeyRef = in.CredentialsSecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPPubSubConfig.
func (in *GCPPubSubConfig) DeepCopy() *GCPPubSubConfig {
	if in == nil {
		return nil
	}
	out := new(GCPPubSubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCSpec) DeepCopyInto(out *GRPCSpec) {
	*out = *in
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCSpec.
func (in *GRPCSpec) DeepCopy() *GRPCSpec {
	if in == nil {
		return nil
	}
	out := new(GRPCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretKeyReference) DeepCopyInto(out *LocalSecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretKeyReference.
func (in *LocalSecretKeyReference) DeepCopy() *LocalSecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MQTTSpec) DeepCopyInto(out *MQTTSpec) {
	*out = *in
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.UserPassRef != nil {
		in, out := &in.UserPassRef, &out.UserPassRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MQTTSpec.
func (in *MQTTSpec) DeepCopy() *MQTTSpec {
	if in == nil {
		return nil
	}
	out := new(MQTTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfig) DeepCopyInto(out *MetricsConfig) {
	*out = *in
	if in.Collect != nil {
		in, out := &in.Collect, &out.Collect
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfig.
func (in *MetricsConfig) DeepCopy() *MetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMeshSpec) DeepCopyInto(out *NetworkMeshSpec) {
	*out = *in
	if in.ExtraAllowedCIDRs != nil {
		in, out := &in.ExtraAllowedCIDRs, &out.ExtraAllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMeshSpec.
func (in *NetworkMeshSpec) DeepCopy() *NetworkMeshSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkMeshSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	in.Mesh.DeepCopyInto(&out.Mesh)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeCertSpec) DeepCopyInto(out *NodeCertSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeCertSpec.
func (in *NodeCertSpec) DeepCopy() *NodeCertSpec {
	if in == nil {
		return nil
	}
	out := new(NodeCertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeClusterRolePermissions) DeepCopyInto(out *NodeClusterRolePermissions) {
	*out = *in
	if in.NodeVerbs != nil {
		in, out := &in.NodeVerbs, &out.NodeVerbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StatusVerbs != nil {
		in, out := &in.StatusVerbs, &out.StatusVerbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeClusterRolePermissions.
func (in *NodeClusterRolePermissions) DeepCopy() *NodeClusterRolePermissions {
	if in == nil {
		return nil
	}
	out := new(NodeClusterRolePermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRBACSpec) DeepCopyInto(out *NodeRBACSpec) {
	*out = *in
	if in.ClusterRolePermissions != nil {
		in, out := &in.ClusterRolePermissions, &out.ClusterRolePermissions
		*out = make(map[string]NodeClusterRolePermissions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRBACSpec.
func (in *NodeRBACSpec) DeepCopy() *NodeRBACSpec {
	if in == nil {
		return nil
	}
	out := new(NodeRBACSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpec) DeepCopyInto(out *NodeSpec) {
	*out = *in
	in.Timers.DeepCopyInto(&out.Timers)
	out.Cert = in.Cert
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]v1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FieldHooks != nil {
		in, out := &in.FieldHooks, &out.FieldHooks
		*out = make([]FieldHook, len(*in))
		copy(*out, *in)
	}
	in.RBAC.DeepCopyInto(&out.RBAC)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpec.
func (in *NodeSpec) DeepCopy() *NodeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTimers) DeepCopyInto(out *NodeTimers) {
	*out = *in
	if in.ForceSyncInterval != nil {
		in, out := &in.ForceSyncInterval, &out.ForceSyncInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTimers.
func (in *NodeTimers) DeepCopy() *NodeTimers {
	if in == nil {
		return nil
	}
	out := new(NodeTimers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeripheralBaseSpec) DeepCopyInto(out *PeripheralBaseSpec) {
	*out = *in
	in.Connector.DeepCopyInto(&out.Connector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeripheralBaseSpec.
func (in *PeripheralBaseSpec) DeepCopy() *PeripheralBaseSpec {
	if in == nil {
		return nil
	}
	out := new(PeripheralBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeripheralConnectivitySpec) DeepCopyInto(out *PeripheralConnectivitySpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(PeripheralConnectivityTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeripheralConnectivitySpec.
func (in *PeripheralConnectivitySpec) DeepCopy() *PeripheralConnectivitySpec {
	if in == nil {
		return nil
	}
	out := new(PeripheralConnectivitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeripheralConnectivityTLSConfig) DeepCopyInto(out *PeripheralConnectivityTLSConfig) {
	*out = *in
	if in.CertSecretRef != nil {
		in, out := &in.CertSecretRef, &out.CertSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NextProtos != nil {
		in, out := &in.NextProtos, &out.NextProtos
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PreSharedKey.DeepCopyInto(&out.PreSharedKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeripheralConnectivityTLSConfig.
func (in *PeripheralConnectivityTLSConfig) DeepCopy() *PeripheralConnectivityTLSConfig {
	if in == nil {
		return nil
	}
	out := new(PeripheralConnectivityTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeripheralConnectivityTLSPreSharedKey) DeepCopyInto(out *PeripheralConnectivityTLSPreSharedKey) {
	*out = *in
	if in.ServerHintMapping != nil {
		in, out := &in.ServerHintMapping, &out.ServerHintMapping
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeripheralConnectivityTLSPreSharedKey.
func (in *PeripheralConnectivityTLSPreSharedKey) DeepCopy() *PeripheralConnectivityTLSPreSharedKey {
	if in == nil {
		return nil
	}
	out := new(PeripheralConnectivityTLSPreSharedKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeripheralMetricSpec) DeepCopyInto(out *PeripheralMetricSpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReporterParams != nil {
		in, out := &in.ReporterParams, &out.ReporterParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeripheralMetricSpec.
func (in *PeripheralMetricSpec) DeepCopy() *PeripheralMetricSpec {
	if in == nil {
		return nil
	}
	out := new(PeripheralMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeripheralOperationSpec) DeepCopyInto(out *PeripheralOperationSpec) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeripheralOperationSpec.
func (in *PeripheralOperationSpec) DeepCopy() *PeripheralOperationSpec {
	if in == nil {
		return nil
	}
	out := new(PeripheralOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeripheralSpec) DeepCopyInto(out *PeripheralSpec) {
	*out = *in
	in.PeripheralBaseSpec.DeepCopyInto(&out.PeripheralBaseSpec)
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]PeripheralOperationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]PeripheralMetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeripheralSpec.
func (in *PeripheralSpec) DeepCopy() *PeripheralSpec {
	if in == nil {
		return nil
	}
	out := new(PeripheralSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDNSConfig) DeepCopyInto(out *PodDNSConfig) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Searches != nil {
		in, out := &in.Searches, &out.Searches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDNSConfig.
func (in *PodDNSConfig) DeepCopy() *PodDNSConfig {
	if in == nil {
		return nil
	}
	out := new(PodDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRBACSpec) DeepCopyInto(out *PodRBACSpec) {
	*out = *in
	if in.RolePermissions != nil {
		in, out := &in.RolePermissions, &out.RolePermissions
		*out = make(map[string]PodRolePermissions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.VirtualPodRolePermissions != nil {
		in, out := &in.VirtualPodRolePermissions, &out.VirtualPodRolePermissions
		*out = make(map[string]PodRolePermissions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRBACSpec.
func (in *PodRBACSpec) DeepCopy() *PodRBACSpec {
	if in == nil {
		return nil
	}
	out := new(PodRBACSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRolePermissions) DeepCopyInto(out *PodRolePermissions) {
	*out = *in
	if in.PodVerbs != nil {
		in, out := &in.PodVerbs, &out.PodVerbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StatusVerbs != nil {
		in, out := &in.StatusVerbs, &out.StatusVerbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowExec != nil {
		in, out := &in.AllowExec, &out.AllowExec
		*out = new(bool)
		**out = **in
	}
	if in.AllowAttach != nil {
		in, out := &in.AllowAttach, &out.AllowAttach
		*out = new(bool)
		**out = **in
	}
	if in.AllowPortForward != nil {
		in, out := &in.AllowPortForward, &out.AllowPortForward
		*out = new(bool)
		**out = **in
	}
	if in.AllowLog != nil {
		in, out := &in.AllowLog, &out.AllowLog
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRolePermissions.
func (in *PodRolePermissions) DeepCopy() *PodRolePermissions {
	if in == nil {
		return nil
	}
	out := new(PodRolePermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpec) DeepCopyInto(out *PodSpec) {
	*out = *in
	in.Timers.DeepCopyInto(&out.Timers)
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(PodDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfig)
		(*in).DeepCopyInto(*out)
	}
	in.RBAC.DeepCopyInto(&out.RBAC)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpec.
func (in *PodSpec) DeepCopy() *PodSpec {
	if in == nil {
		return nil
	}
	out := new(PodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTimers) DeepCopyInto(out *PodTimers) {
	*out = *in
	if in.ForceSyncInterval != nil {
		in, out := &in.ForceSyncInterval, &out.ForceSyncInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTimers.
func (in *PodTimers) DeepCopy() *PodTimers {
	if in == nil {
		return nil
	}
	out := new(PodTimers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
